CC = gcc
INCLUDE := -I../include
# LDFLAGS := -L../lib
# LDLIBS  := -ltlp -lpthread
# CFLAGS  := -g -Wall $(INCLUDE) ../.config
# CFLAGS  += -save-temps=obj

CFLAGS := -std=gnu89

PROGNAME = print_offset print_offset_restore

all: $(PROGNAME)

clean:
	rm -rf *.o
	rm -rf $(PROGNAME)
	rm -rf *.dSYM
